name: Android Build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew exec
        run: chmod +x ./source/gradlew

      - name: Run Tests
        run: bash ./source/gradlew test

      - name: Build Project Android
        run: bash ./source/gradlew assemble
