name: Android Build

on:
  pull_request:
    branches:
      - develop
      
defaults:
  run:
    working-directory: source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew exec
        run: chmod +x ./gradlew

      - name: Run Tests
        run: bash ./gradlew test

      - name: Build Project Android
        run: bash ./gradlew assemble
